import { OBD2Service, PIDDataType } from '../../types';
import { ManufacturerPID } from './ford';

/** BMW manufacturer-specific PIDs */
export const BMW_PIDS: ManufacturerPID[] = [
  {
    pid: 0x224000,
    service: OBD2Service.CURRENT_DATA,
    name: 'BMW VANOS Position Intake',
    description: 'VANOS variable valve timing intake position (BMW)',
    unit: '°',
    dataType: PIDDataType.INT8,
    min: -30,
    max: 60,
    formula: 'A - 30',
    byteCount: 1,
    manufacturer: 'BMW',
    moduleId: 'DME',
    protocol: 'ISO_15765',
  },
  {
    pid: 0x224001,
    service: OBD2Service.CURRENT_DATA,
    name: 'BMW VANOS Position Exhaust',
    description: 'VANOS variable valve timing exhaust position (BMW)',
    unit: '°',
    dataType: PIDDataType.INT8,
    min: -30,
    max: 60,
    formula: 'A - 30',
    byteCount: 1,
    manufacturer: 'BMW',
    moduleId: 'DME',
    protocol: 'ISO_15765',
  },
  {
    pid: 0x224002,
    service: OBD2Service.CURRENT_DATA,
    name: 'BMW Oil Condition',
    description: 'Engine oil quality/condition percentage (BMW CBS)',
    unit: '%',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 100,
    formula: 'A',
    byteCount: 1,
    manufacturer: 'BMW',
    moduleId: 'DME',
    protocol: 'ISO_15765',
  },
  {
    pid: 0x224003,
    service: OBD2Service.CURRENT_DATA,
    name: 'BMW Valvetronic Position',
    description: 'Valvetronic eccentric shaft position (BMW)',
    unit: '°',
    dataType: PIDDataType.INT16,
    min: -360,
    max: 360,
    formula: '((A * 256) + B) - 360',
    byteCount: 2,
    manufacturer: 'BMW',
    moduleId: 'DME',
    protocol: 'ISO_15765',
  },
  {
    pid: 0x224004,
    service: OBD2Service.CURRENT_DATA,
    name: 'BMW Turbo Wastegate Position',
    description: 'Wastegate position for turbocharged BMW engine',
    unit: '%',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 100,
    formula: 'A * 100 / 255',
    byteCount: 1,
    manufacturer: 'BMW',
    moduleId: 'DME',
    protocol: 'ISO_15765',
  },
  {
    pid: 0x224005,
    service: OBD2Service.CURRENT_DATA,
    name: 'BMW Charge Air Temperature',
    description: 'Intercooler charge air temperature (BMW)',
    unit: '°C',
    dataType: PIDDataType.UINT8,
    min: -40,
    max: 215,
    formula: 'A - 40',
    byteCount: 1,
    manufacturer: 'BMW',
    moduleId: 'DME',
    protocol: 'ISO_15765',
  },
  {
    pid: 0x224006,
    service: OBD2Service.CURRENT_DATA,
    name: 'BMW EfficientDynamics Mode',
    description: 'Current driving/efficiency mode (BMW ED)',
    unit: '',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 5,
    formula: 'A',
    byteCount: 1,
    manufacturer: 'BMW',
    moduleId: 'DME',
    protocol: 'ISO_15765',
  },
];
