import { OBD2Service, PIDDataType } from '../../types';
import { ManufacturerPID } from './ford';

/**
 * BMW Extended PIDs - JTAG/CAN, E-series ID, DME/DDE tuning, NCD coding
 */
export const BMW_EXTENDED_PIDS: ManufacturerPID[] = [
  // DME/DDE extended PIDs
  {
    pid: 0x224100,
    service: OBD2Service.CURRENT_DATA,
    name: 'BMW DME Fuel Mixture Adaptation',
    description: 'Additive fuel mixture adaptation (BMW DME)',
    unit: '%',
    dataType: PIDDataType.INT16,
    min: -25,
    max: 25,
    formula: '((A * 256) + B) * 0.1 - 25',
    byteCount: 2,
    manufacturer: 'BMW',
    moduleId: 'DME',
    protocol: 'CAN',
  },
  {
    pid: 0x224101,
    service: OBD2Service.CURRENT_DATA,
    name: 'BMW DDE Rail Pressure Actual',
    description: 'Common-rail injection pressure actual value (BMW DDE diesel)',
    unit: 'bar',
    dataType: PIDDataType.UINT16,
    min: 0,
    max: 2000,
    formula: '((A * 256) + B)',
    byteCount: 2,
    manufacturer: 'BMW',
    moduleId: 'DDE',
    protocol: 'CAN',
  },
  {
    pid: 0x224102,
    service: OBD2Service.CURRENT_DATA,
    name: 'BMW E-series ZCS Coding',
    description: 'E-series central coding (ZCS) current value',
    unit: '',
    dataType: PIDDataType.UINT32,
    min: 0,
    max: 4294967295,
    formula: '(A << 24) | (B << 16) | (C << 8) | D',
    byteCount: 4,
    manufacturer: 'BMW',
    moduleId: 'ZCS',
    protocol: 'CAN',
  },
  // NCD (Network Coded Data) identifiers
  {
    pid: 0x224103,
    service: OBD2Service.CURRENT_DATA,
    name: 'BMW NCD Activation Status',
    description: 'Network coded data optional feature activation',
    unit: '',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 255,
    formula: 'A',
    byteCount: 1,
    manufacturer: 'BMW',
    moduleId: 'ZGW',
    protocol: 'CAN',
  },
  // Tuning / write PIDs
  {
    pid: 0x2E4100,
    service: OBD2Service.CONTROL_OPERATION,
    name: 'BMW Write Boost Target Pressure',
    description: 'Write boost target pressure for tuning (BMW DME)',
    unit: 'mbar',
    dataType: PIDDataType.UINT16,
    min: 800,
    max: 3000,
    formula: '(A * 256) + B',
    byteCount: 2,
    manufacturer: 'BMW',
    moduleId: 'DME',
    protocol: 'CAN',
  },
  {
    pid: 0x2E4101,
    service: OBD2Service.CONTROL_OPERATION,
    name: 'BMW Write VANOS Map Selection',
    description: 'Write VANOS cam timing map selection (BMW DME)',
    unit: '',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 3,
    formula: 'A',
    byteCount: 1,
    manufacturer: 'BMW',
    moduleId: 'DME',
    protocol: 'CAN',
  },
  {
    pid: 0x224104,
    service: OBD2Service.CURRENT_DATA,
    name: 'BMW JTAG Firmware Version',
    description: 'DME firmware version read via JTAG/CAN',
    unit: '',
    dataType: PIDDataType.STRING,
    min: 0,
    max: 0,
    formula: 'ASCII',
    byteCount: 8,
    manufacturer: 'BMW',
    moduleId: 'DME',
    protocol: 'JTAG',
  },
];
