import { OBD2Service, PIDDataType } from '../../types';
import { ManufacturerPID } from './ford';

/**
 * Ford Extended PIDs - FORScan mode 0x22/0x2E identifiers
 * Used with FORScan and ELM327/J2534 via ISO_15765 CAN
 */
export const FORD_EXTENDED_PIDS: ManufacturerPID[] = [
  // FORScan PCM extended PIDs (7E0 module)
  {
    pid: 0x220101,
    service: OBD2Service.CURRENT_DATA,
    name: 'Ford PCM Battery Voltage (Extended)',
    description: 'PCM-measured battery voltage via FORScan extended mode',
    unit: 'V',
    dataType: PIDDataType.UINT16,
    min: 0,
    max: 65,
    formula: '((A * 256) + B) * 0.001',
    byteCount: 2,
    manufacturer: 'Ford',
    moduleId: '7E0',
    protocol: 'FORScan',
  },
  {
    pid: 0x220102,
    service: OBD2Service.CURRENT_DATA,
    name: 'Ford Auxiliary Battery Voltage',
    description: 'Dual-battery auxiliary 12V battery voltage (Ford hybrid/PHEV)',
    unit: 'V',
    dataType: PIDDataType.UINT16,
    min: 0,
    max: 20,
    formula: '((A * 256) + B) * 0.01',
    byteCount: 2,
    manufacturer: 'Ford',
    moduleId: 'BMS',
    protocol: 'FORScan',
  },
  // SCP/CCL protocol identifiers (older Ford vehicles)
  {
    pid: 0x220103,
    service: OBD2Service.CURRENT_DATA,
    name: 'Ford SCP Transmission Input Speed',
    description: 'Transmission input shaft speed via SCP protocol (Ford)',
    unit: 'RPM',
    dataType: PIDDataType.UINT16,
    min: 0,
    max: 8000,
    formula: '((A * 256) + B)',
    byteCount: 2,
    manufacturer: 'Ford',
    moduleId: 'TCM',
    protocol: 'SCP',
  },
  {
    pid: 0x220104,
    service: OBD2Service.CURRENT_DATA,
    name: 'Ford SCP Transmission Output Speed',
    description: 'Transmission output shaft speed via SCP protocol (Ford)',
    unit: 'RPM',
    dataType: PIDDataType.UINT16,
    min: 0,
    max: 8000,
    formula: '((A * 256) + B)',
    byteCount: 2,
    manufacturer: 'Ford',
    moduleId: 'TCM',
    protocol: 'SCP',
  },
  // Transmission tuning
  {
    pid: 0x220105,
    service: OBD2Service.CURRENT_DATA,
    name: 'Ford Transmission Shift Pressure',
    description: 'Line pressure during shift events (Ford)',
    unit: 'kPa',
    dataType: PIDDataType.UINT16,
    min: 0,
    max: 2000,
    formula: '((A * 256) + B) * 0.5',
    byteCount: 2,
    manufacturer: 'Ford',
    moduleId: 'TCM',
    protocol: 'FORScan',
  },
  {
    pid: 0x220106,
    service: OBD2Service.CURRENT_DATA,
    name: 'Ford Trans Clutch Slip Speed',
    description: 'Torque converter clutch slip speed (Ford)',
    unit: 'RPM',
    dataType: PIDDataType.INT16,
    min: -500,
    max: 500,
    formula: '((A * 256) + B) - 500',
    byteCount: 2,
    manufacturer: 'Ford',
    moduleId: 'TCM',
    protocol: 'FORScan',
  },
  // Write (0x2E) identifiers for tuning
  {
    pid: 0x2E0101,
    service: OBD2Service.CONTROL_OPERATION,
    name: 'Ford Write Idle Target RPM',
    description: 'Write idle target RPM to PCM (FORScan)',
    unit: 'RPM',
    dataType: PIDDataType.UINT16,
    min: 500,
    max: 1200,
    formula: 'A',
    byteCount: 2,
    manufacturer: 'Ford',
    moduleId: '7E0',
    protocol: 'FORScan',
  },
];
