import { PIDDefinition, OBD2Service, PIDDataType } from '../../types';

/** Extended PID definition for manufacturer-specific PIDs */
export interface ManufacturerPID extends PIDDefinition {
  manufacturer: string;
  moduleId?: string;
  protocol?: string;
}

/** Ford manufacturer-specific PIDs */
export const FORD_PIDS: ManufacturerPID[] = [
  {
    pid: 0x22F401,
    service: OBD2Service.CURRENT_DATA,
    name: 'Ford Transmission Oil Temperature',
    description: 'Ford-specific transmission oil temperature via PCM',
    unit: '°C',
    dataType: PIDDataType.UINT8,
    min: -40,
    max: 215,
    formula: 'A - 40',
    byteCount: 1,
    manufacturer: 'Ford',
    moduleId: 'PCM',
    protocol: 'ISO_15765',
  },
  {
    pid: 0x22F402,
    service: OBD2Service.CURRENT_DATA,
    name: 'Ford Transmission Gear',
    description: 'Current transmission gear position',
    unit: '',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 8,
    formula: 'A',
    byteCount: 1,
    manufacturer: 'Ford',
    moduleId: 'TCM',
    protocol: 'ISO_15765',
  },
  {
    pid: 0x22F403,
    service: OBD2Service.CURRENT_DATA,
    name: 'Ford Brake Pressure',
    description: 'Brake master cylinder pressure',
    unit: 'kPa',
    dataType: PIDDataType.UINT16,
    min: 0,
    max: 25000,
    formula: '((A * 256) + B) * 0.1',
    byteCount: 2,
    manufacturer: 'Ford',
    moduleId: 'ABS',
    protocol: 'ISO_15765',
  },
  {
    pid: 0x22F404,
    service: OBD2Service.CURRENT_DATA,
    name: 'Ford Battery Voltage',
    description: 'High-voltage battery state (Ford hybrid)',
    unit: 'V',
    dataType: PIDDataType.UINT16,
    min: 0,
    max: 400,
    formula: '((A * 256) + B) * 0.1',
    byteCount: 2,
    manufacturer: 'Ford',
    moduleId: 'BMS',
    protocol: 'ISO_15765',
  },
  {
    pid: 0x22F405,
    service: OBD2Service.CURRENT_DATA,
    name: 'Ford BARO Sensor',
    description: 'Barometric pressure (Ford-specific)',
    unit: 'kPa',
    dataType: PIDDataType.UINT8,
    min: 60,
    max: 110,
    formula: 'A * 0.5 + 60',
    byteCount: 1,
    manufacturer: 'Ford',
    moduleId: 'PCM',
    protocol: 'ISO_15765',
  },
  {
    pid: 0x22F406,
    service: OBD2Service.CURRENT_DATA,
    name: 'Ford Commanded Spark Timing',
    description: 'Commanded ignition spark timing (Ford)',
    unit: '°',
    dataType: PIDDataType.INT16,
    min: -64,
    max: 64,
    formula: '((A * 256) + B) / 10 - 64',
    byteCount: 2,
    manufacturer: 'Ford',
    moduleId: 'PCM',
    protocol: 'ISO_15765',
  },
  {
    pid: 0x22F407,
    service: OBD2Service.CURRENT_DATA,
    name: 'Ford Idle Air Control Position',
    description: 'Idle air control motor position (Ford)',
    unit: 'steps',
    dataType: PIDDataType.UINT16,
    min: 0,
    max: 512,
    formula: '(A * 256) + B',
    byteCount: 2,
    manufacturer: 'Ford',
    moduleId: 'PCM',
    protocol: 'ISO_15765',
  },
  {
    pid: 0x22F408,
    service: OBD2Service.CURRENT_DATA,
    name: 'Ford Knock Sensor',
    description: 'Knock sensor activity (Ford)',
    unit: '',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 255,
    formula: 'A',
    byteCount: 1,
    manufacturer: 'Ford',
    moduleId: 'PCM',
    protocol: 'ISO_15765',
  },
];
