import { OBD2Service, PIDDataType } from '../../types';
import { ManufacturerPID } from './ford';

/** GM manufacturer-specific PIDs */
export const GM_PIDS: ManufacturerPID[] = [
  {
    pid: 0x22100A,
    service: OBD2Service.CURRENT_DATA,
    name: 'GM Desired Idle RPM',
    description: 'GM-specific desired idle speed from PCM',
    unit: 'RPM',
    dataType: PIDDataType.UINT16,
    min: 0,
    max: 3000,
    formula: '((A * 256) + B) * 0.5',
    byteCount: 2,
    manufacturer: 'GM',
    moduleId: 'ECM',
    protocol: 'ISO_15765',
  },
  {
    pid: 0x221001,
    service: OBD2Service.CURRENT_DATA,
    name: 'GM APP Sensor 1',
    description: 'Accelerator pedal position sensor 1 (GM)',
    unit: '%',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 100,
    formula: 'A * 100 / 255',
    byteCount: 1,
    manufacturer: 'GM',
    moduleId: 'ECM',
    protocol: 'ISO_15765',
  },
  {
    pid: 0x221002,
    service: OBD2Service.CURRENT_DATA,
    name: 'GM APP Sensor 2',
    description: 'Accelerator pedal position sensor 2 (GM)',
    unit: '%',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 100,
    formula: 'A * 100 / 255',
    byteCount: 1,
    manufacturer: 'GM',
    moduleId: 'ECM',
    protocol: 'ISO_15765',
  },
  {
    pid: 0x221003,
    service: OBD2Service.CURRENT_DATA,
    name: 'GM Torque Management Reduction',
    description: 'Engine torque reduction request from TCM',
    unit: '%',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 100,
    formula: 'A * 100 / 255',
    byteCount: 1,
    manufacturer: 'GM',
    moduleId: 'TCM',
    protocol: 'ISO_15765',
  },
  {
    pid: 0x221004,
    service: OBD2Service.CURRENT_DATA,
    name: 'GM TAC Motor Position',
    description: 'Throttle actuator control motor position (GM)',
    unit: '%',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 100,
    formula: 'A * 100 / 255',
    byteCount: 1,
    manufacturer: 'GM',
    moduleId: 'ECM',
    protocol: 'ISO_15765',
  },
  {
    pid: 0x221005,
    service: OBD2Service.CURRENT_DATA,
    name: 'GM Camshaft Position Actuator',
    description: 'Variable valve timing actuator position (GM)',
    unit: '°',
    dataType: PIDDataType.INT8,
    min: -30,
    max: 30,
    formula: 'A - 30',
    byteCount: 1,
    manufacturer: 'GM',
    moduleId: 'ECM',
    protocol: 'ISO_15765',
  },
  {
    pid: 0x221006,
    service: OBD2Service.CURRENT_DATA,
    name: 'GM Supercharger Boost Pressure',
    description: 'Supercharger inlet boost pressure (GM)',
    unit: 'kPa',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 255,
    formula: 'A',
    byteCount: 1,
    manufacturer: 'GM',
    moduleId: 'ECM',
    protocol: 'ISO_15765',
  },
];
