import { OBD2Service, PIDDataType } from '../../types';
import { ManufacturerPID } from './ford';

/**
 * GM Extended PIDs - GMLAN protocol, E38 module, RPO codes, performance maps
 */
export const GM_EXTENDED_PIDS: ManufacturerPID[] = [
  // GMLAN high-speed CAN extended PIDs
  {
    pid: 0x222001,
    service: OBD2Service.CURRENT_DATA,
    name: 'GM GMLAN Engine Torque Request',
    description: 'Engine torque request from driver interface (GMLAN)',
    unit: 'Nm',
    dataType: PIDDataType.UINT16,
    min: 0,
    max: 1000,
    formula: '((A * 256) + B) * 0.5',
    byteCount: 2,
    manufacturer: 'GM',
    moduleId: 'E38 ECM',
    protocol: 'GMLAN',
  },
  {
    pid: 0x222002,
    service: OBD2Service.CURRENT_DATA,
    name: 'GM GMLAN Transmission Temperature',
    description: 'Transmission fluid temperature (GMLAN)',
    unit: '°C',
    dataType: PIDDataType.UINT8,
    min: -40,
    max: 215,
    formula: 'A - 40',
    byteCount: 1,
    manufacturer: 'GM',
    moduleId: 'TCM',
    protocol: 'GMLAN',
  },
  // E38 module PIDs
  {
    pid: 0x222003,
    service: OBD2Service.CURRENT_DATA,
    name: 'GM E38 Fuel Rail Pressure',
    description: 'Direct injection fuel rail pressure (E38 ECM)',
    unit: 'MPa',
    dataType: PIDDataType.UINT16,
    min: 0,
    max: 20,
    formula: '((A * 256) + B) * 0.001',
    byteCount: 2,
    manufacturer: 'GM',
    moduleId: 'E38 ECM',
    protocol: 'GMLAN',
  },
  {
    pid: 0x222004,
    service: OBD2Service.CURRENT_DATA,
    name: 'GM E38 Estimated Catalyst Temperature',
    description: 'Estimated catalytic converter temperature (E38)',
    unit: '°C',
    dataType: PIDDataType.UINT16,
    min: 0,
    max: 1200,
    formula: '((A * 256) + B) * 0.1',
    byteCount: 2,
    manufacturer: 'GM',
    moduleId: 'E38 ECM',
    protocol: 'GMLAN',
  },
  // RPO code performance maps
  {
    pid: 0x222005,
    service: OBD2Service.CURRENT_DATA,
    name: 'GM Performance Mode Status',
    description: 'Active performance mode RPO code selection',
    unit: '',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 3,
    formula: 'A',
    byteCount: 1,
    manufacturer: 'GM',
    moduleId: 'BCM',
    protocol: 'GMLAN',
  },
  {
    pid: 0x222006,
    service: OBD2Service.CURRENT_DATA,
    name: 'GM Magnetic Ride Control Damper',
    description: 'MRC damper position/stiffness (GM)',
    unit: '%',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 100,
    formula: 'A * 100 / 255',
    byteCount: 1,
    manufacturer: 'GM',
    moduleId: 'SWPS',
    protocol: 'GMLAN',
  },
  // Write PIDs for performance tuning
  {
    pid: 0x2E2001,
    service: OBD2Service.CONTROL_OPERATION,
    name: 'GM Write Rev Limiter',
    description: 'Write rev limiter setpoint (GMLAN, requires security access)',
    unit: 'RPM',
    dataType: PIDDataType.UINT16,
    min: 4000,
    max: 8000,
    formula: '(A * 256) + B',
    byteCount: 2,
    manufacturer: 'GM',
    moduleId: 'E38 ECM',
    protocol: 'GMLAN',
  },
];
