import { OBD2Service, PIDDataType } from '../../types';
import { ManufacturerPID } from './ford';

/** Toyota manufacturer-specific PIDs */
export const TOYOTA_PIDS: ManufacturerPID[] = [
  {
    pid: 0x22CA,
    service: OBD2Service.CURRENT_DATA,
    name: 'Toyota Coolant Temperature (ECT2)',
    description: 'Secondary engine coolant temperature sensor (Toyota)',
    unit: '°C',
    dataType: PIDDataType.UINT8,
    min: -40,
    max: 215,
    formula: 'A - 40',
    byteCount: 1,
    manufacturer: 'Toyota',
    moduleId: 'ECM',
    protocol: 'ISO_15765',
  },
  {
    pid: 0x22CB,
    service: OBD2Service.CURRENT_DATA,
    name: 'Toyota VVT-i Advance Angle (Bank 1)',
    description: 'Variable Valve Timing advance angle bank 1 (Toyota)',
    unit: '°',
    dataType: PIDDataType.INT8,
    min: -30,
    max: 50,
    formula: 'A - 30',
    byteCount: 1,
    manufacturer: 'Toyota',
    moduleId: 'ECM',
    protocol: 'ISO_15765',
  },
  {
    pid: 0x22CC,
    service: OBD2Service.CURRENT_DATA,
    name: 'Toyota VVT-i Advance Angle (Bank 2)',
    description: 'Variable Valve Timing advance angle bank 2 (Toyota)',
    unit: '°',
    dataType: PIDDataType.INT8,
    min: -30,
    max: 50,
    formula: 'A - 30',
    byteCount: 1,
    manufacturer: 'Toyota',
    moduleId: 'ECM',
    protocol: 'ISO_15765',
  },
  {
    pid: 0x22CD,
    service: OBD2Service.CURRENT_DATA,
    name: 'Toyota Hybrid Battery State of Charge',
    description: 'High-voltage battery SOC (Toyota Hybrid)',
    unit: '%',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 100,
    formula: 'A * 100 / 255',
    byteCount: 1,
    manufacturer: 'Toyota',
    moduleId: 'HV ECU',
    protocol: 'ISO_15765',
  },
  {
    pid: 0x22CE,
    service: OBD2Service.CURRENT_DATA,
    name: 'Toyota MG1 Torque',
    description: 'Motor/generator 1 torque (Toyota Hybrid)',
    unit: 'Nm',
    dataType: PIDDataType.INT16,
    min: -500,
    max: 500,
    formula: '((A * 256) + B) - 500',
    byteCount: 2,
    manufacturer: 'Toyota',
    moduleId: 'HV ECU',
    protocol: 'ISO_15765',
  },
  {
    pid: 0x22CF,
    service: OBD2Service.CURRENT_DATA,
    name: 'Toyota MG2 Torque',
    description: 'Motor/generator 2 torque (Toyota Hybrid)',
    unit: 'Nm',
    dataType: PIDDataType.INT16,
    min: -500,
    max: 500,
    formula: '((A * 256) + B) - 500',
    byteCount: 2,
    manufacturer: 'Toyota',
    moduleId: 'HV ECU',
    protocol: 'ISO_15765',
  },
  {
    pid: 0x22D0,
    service: OBD2Service.CURRENT_DATA,
    name: 'Toyota EGR Valve Position',
    description: 'EGR valve opening percentage (Toyota)',
    unit: '%',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 100,
    formula: 'A * 100 / 255',
    byteCount: 1,
    manufacturer: 'Toyota',
    moduleId: 'ECM',
    protocol: 'ISO_15765',
  },
];
