import { OBD2Service, PIDDataType } from '../../types';
import { ManufacturerPID } from './ford';

/**
 * Toyota Extended PIDs - SSM2 protocol, hybrid system, CAN 500K, transmission learning
 */
export const TOYOTA_EXTENDED_PIDS: ManufacturerPID[] = [
  // SSM2 (Subaru Select Monitor 2) compatible / Toyota SST protocol
  {
    pid: 0x22D100,
    service: OBD2Service.CURRENT_DATA,
    name: 'Toyota SSM2 Injector Duty Cycle',
    description: 'Injector duty cycle percentage (Toyota SSM2)',
    unit: '%',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 100,
    formula: 'A * 100 / 255',
    byteCount: 1,
    manufacturer: 'Toyota',
    moduleId: 'ECM',
    protocol: 'SSM2',
  },
  {
    pid: 0x22D101,
    service: OBD2Service.CURRENT_DATA,
    name: 'Toyota Hybrid Inverter Temperature',
    description: 'Hybrid inverter cooling temperature (Toyota Prius/Lexus hybrid)',
    unit: '°C',
    dataType: PIDDataType.UINT8,
    min: -40,
    max: 150,
    formula: 'A - 40',
    byteCount: 1,
    manufacturer: 'Toyota',
    moduleId: 'HV ECU',
    protocol: 'CAN_500K',
  },
  {
    pid: 0x22D102,
    service: OBD2Service.CURRENT_DATA,
    name: 'Toyota Hybrid Motor Speed',
    description: 'Electric motor rotational speed (Toyota Hybrid)',
    unit: 'RPM',
    dataType: PIDDataType.UINT16,
    min: -10000,
    max: 10000,
    formula: '((A * 256) + B) - 10000',
    byteCount: 2,
    manufacturer: 'Toyota',
    moduleId: 'HV ECU',
    protocol: 'CAN_500K',
  },
  {
    pid: 0x22D103,
    service: OBD2Service.CURRENT_DATA,
    name: 'Toyota HV Battery Current',
    description: 'High-voltage battery current draw (Toyota Hybrid)',
    unit: 'A',
    dataType: PIDDataType.INT16,
    min: -300,
    max: 300,
    formula: '((A * 256) + B) - 300',
    byteCount: 2,
    manufacturer: 'Toyota',
    moduleId: 'HV ECU',
    protocol: 'CAN_500K',
  },
  // Transmission learning data
  {
    pid: 0x22D104,
    service: OBD2Service.CURRENT_DATA,
    name: 'Toyota CVT Belt Tension',
    description: 'CVT belt tension learning value (Toyota CVT)',
    unit: 'N',
    dataType: PIDDataType.UINT16,
    min: 0,
    max: 20000,
    formula: '((A * 256) + B)',
    byteCount: 2,
    manufacturer: 'Toyota',
    moduleId: 'TCM',
    protocol: 'CAN_500K',
  },
  {
    pid: 0x22D105,
    service: OBD2Service.CURRENT_DATA,
    name: 'Toyota AT Fluid Deterioration',
    description: 'Automatic transmission fluid deterioration indicator',
    unit: '%',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 100,
    formula: 'A',
    byteCount: 1,
    manufacturer: 'Toyota',
    moduleId: 'TCM',
    protocol: 'CAN_500K',
  },
  // Write/control PIDs
  {
    pid: 0x2ED100,
    service: OBD2Service.CONTROL_OPERATION,
    name: 'Toyota Write AT Learning Reset',
    description: 'Reset automatic transmission learning values',
    unit: '',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 1,
    formula: 'A',
    byteCount: 1,
    manufacturer: 'Toyota',
    moduleId: 'TCM',
    protocol: 'CAN_500K',
  },
];
