import { OBD2Service, PIDDataType } from '../../types';
import { ManufacturerPID } from './ford';

/** VW/Audi manufacturer-specific PIDs */
export const VW_PIDS: ManufacturerPID[] = [
  {
    pid: 0x221000,
    service: OBD2Service.CURRENT_DATA,
    name: 'VW Engine Torque',
    description: 'Actual engine torque output (VW/Audi)',
    unit: 'Nm',
    dataType: PIDDataType.UINT16,
    min: 0,
    max: 1000,
    formula: '((A * 256) + B) - 200',
    byteCount: 2,
    manufacturer: 'VW',
    moduleId: 'Engine ECU',
    protocol: 'ISO_15765',
  },
  {
    pid: 0x221001,
    service: OBD2Service.CURRENT_DATA,
    name: 'VW Turbocharger Boost Pressure',
    description: 'Requested and actual turbocharger boost (VW/Audi)',
    unit: 'mbar',
    dataType: PIDDataType.UINT16,
    min: 0,
    max: 3000,
    formula: '((A * 256) + B)',
    byteCount: 2,
    manufacturer: 'VW',
    moduleId: 'Engine ECU',
    protocol: 'ISO_15765',
  },
  {
    pid: 0x221002,
    service: OBD2Service.CURRENT_DATA,
    name: 'VW DSG Gear Position',
    description: 'Current DSG/S-tronic transmission gear (VW/Audi)',
    unit: '',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 8,
    formula: 'A',
    byteCount: 1,
    manufacturer: 'VW',
    moduleId: 'Gearbox ECU',
    protocol: 'ISO_15765',
  },
  {
    pid: 0x221003,
    service: OBD2Service.CURRENT_DATA,
    name: 'VW DPF Soot Load',
    description: 'Diesel particulate filter soot load (VW diesel)',
    unit: '%',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 100,
    formula: 'A * 100 / 255',
    byteCount: 1,
    manufacturer: 'VW',
    moduleId: 'Engine ECU',
    protocol: 'ISO_15765',
  },
  {
    pid: 0x221004,
    service: OBD2Service.CURRENT_DATA,
    name: 'VW Injector Quantity',
    description: 'Diesel injector quantity per stroke (VW TDI)',
    unit: 'mg/stroke',
    dataType: PIDDataType.UINT16,
    min: 0,
    max: 200,
    formula: '((A * 256) + B) * 0.01',
    byteCount: 2,
    manufacturer: 'VW',
    moduleId: 'Engine ECU',
    protocol: 'ISO_15765',
  },
  {
    pid: 0x221005,
    service: OBD2Service.CURRENT_DATA,
    name: 'VW Glow Plug Temperature',
    description: 'Glow plug temperature (VW diesel)',
    unit: '°C',
    dataType: PIDDataType.UINT16,
    min: 0,
    max: 1200,
    formula: '((A * 256) + B) * 0.1',
    byteCount: 2,
    manufacturer: 'VW',
    moduleId: 'Engine ECU',
    protocol: 'ISO_15765',
  },
];
