import { OBD2Service, PIDDataType } from '../../types';
import { ManufacturerPID } from './ford';

/**
 * VW/Audi Extended PIDs - VAG KKL/UDS, component protection, coding/adaptation, DPF regen
 */
export const VW_EXTENDED_PIDS: ManufacturerPID[] = [
  // VAG UDS extended diagnostics
  {
    pid: 0x222000,
    service: OBD2Service.CURRENT_DATA,
    name: 'VAG Actual Torque',
    description: 'Actual engine torque in percent of maximum (VAG UDS)',
    unit: '%',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 150,
    formula: 'A',
    byteCount: 1,
    manufacturer: 'VW',
    moduleId: 'Engine ECU',
    protocol: 'UDS',
  },
  {
    pid: 0x222001,
    service: OBD2Service.CURRENT_DATA,
    name: 'VAG DSG Clutch Temperature',
    description: 'DSG/S-tronic dual clutch temperature (VAG)',
    unit: '°C',
    dataType: PIDDataType.UINT16,
    min: -40,
    max: 350,
    formula: '((A * 256) + B) - 40',
    byteCount: 2,
    manufacturer: 'VW',
    moduleId: 'Gearbox ECU',
    protocol: 'UDS',
  },
  // DPF regeneration data
  {
    pid: 0x222002,
    service: OBD2Service.CURRENT_DATA,
    name: 'VAG DPF Differential Pressure',
    description: 'Diesel particulate filter differential pressure (VAG TDI)',
    unit: 'mbar',
    dataType: PIDDataType.UINT16,
    min: 0,
    max: 2000,
    formula: '((A * 256) + B)',
    byteCount: 2,
    manufacturer: 'VW',
    moduleId: 'Engine ECU',
    protocol: 'UDS',
  },
  {
    pid: 0x222003,
    service: OBD2Service.CURRENT_DATA,
    name: 'VAG DPF Regeneration Status',
    description: 'Active DPF regeneration status (VAG TDI)',
    unit: '',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 3,
    formula: 'A',
    byteCount: 1,
    manufacturer: 'VW',
    moduleId: 'Engine ECU',
    protocol: 'UDS',
  },
  // Component protection / coding
  {
    pid: 0x222004,
    service: OBD2Service.CURRENT_DATA,
    name: 'VAG Component Protection Status',
    description: 'Component protection activation state (VAG ODIS)',
    unit: '',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 1,
    formula: 'A',
    byteCount: 1,
    manufacturer: 'VW',
    moduleId: 'BCM',
    protocol: 'UDS',
  },
  {
    pid: 0x222005,
    service: OBD2Service.CURRENT_DATA,
    name: 'VAG Adaptation Channel Value',
    description: 'Adaptation channel data (VAG KKL/UDS)',
    unit: '',
    dataType: PIDDataType.UINT16,
    min: 0,
    max: 65535,
    formula: '(A * 256) + B',
    byteCount: 2,
    manufacturer: 'VW',
    moduleId: 'Engine ECU',
    protocol: 'KKL',
  },
  // Write/coding PIDs
  {
    pid: 0x2E2001,
    service: OBD2Service.CONTROL_OPERATION,
    name: 'VAG Write ECU Coding',
    description: 'Write long coding byte to ECU (VAG ODIS/VCDS)',
    unit: '',
    dataType: PIDDataType.UINT32,
    min: 0,
    max: 4294967295,
    formula: '(A << 24) | (B << 16) | (C << 8) | D',
    byteCount: 4,
    manufacturer: 'VW',
    moduleId: 'Engine ECU',
    protocol: 'UDS',
  },
];
