/**
 * OBD2 protocol constants, service IDs, and common PID definitions
 */
import { OBD2Service, PIDDataType, PIDDefinition } from '../types/pid';

/** ELM327 AT commands */
export const ELM327_COMMANDS = {
  RESET: 'ATZ',
  ECHO_OFF: 'ATE0',
  ECHO_ON: 'ATE1',
  LINEFEEDS_OFF: 'ATL0',
  LINEFEEDS_ON: 'ATL1',
  HEADERS_OFF: 'ATH0',
  HEADERS_ON: 'ATH1',
  SPACES_OFF: 'ATS0',
  SPACES_ON: 'ATS1',
  PROTOCOL_AUTO: 'ATSP0',
  PROTOCOL_1: 'ATSP1',
  PROTOCOL_2: 'ATSP2',
  PROTOCOL_3: 'ATSP3',
  PROTOCOL_4: 'ATSP4',
  PROTOCOL_5: 'ATSP5',
  PROTOCOL_6: 'ATSP6',
  PROTOCOL_7: 'ATSP7',
  PROTOCOL_8: 'ATSP8',
  PROTOCOL_9: 'ATSP9',
  DESCRIBE_PROTOCOL: 'ATDP',
  DESCRIBE_PROTOCOL_NUM: 'ATDPN',
  READ_VOLTAGE: 'ATRV',
  DEVICE_INFO: 'ATI',
  ADAPTIVE_TIMING_0: 'ATAT0',
  ADAPTIVE_TIMING_1: 'ATAT1',
  ADAPTIVE_TIMING_2: 'ATAT2',
  SET_TIMEOUT: (timeout: number): string =>
    `ATST${timeout.toString(16).padStart(2, '0').toUpperCase()}`,
} as const;

/** ELM327 response strings */
export const ELM327_RESPONSES = {
  OK: 'OK',
  ERROR: 'ERROR',
  NO_DATA: 'NO DATA',
  SEARCHING: 'SEARCHING...',
  UNABLE_TO_CONNECT: 'UNABLE TO CONNECT',
  BUS_INIT_ERROR: 'BUS INIT: ERROR',
  BUS_ERROR: 'BUS ERROR',
  STOPPED: 'STOPPED',
  ELM327: 'ELM327',
  PROMPT: '>',
} as const;

/** OBD2 response byte prefixes */
export const OBD2_RESPONSE_PREFIX = {
  POSITIVE: 0x40,
  NEGATIVE: 0x7F,
  NRC_SERVICE_NOT_SUPPORTED: 0x11,
  NRC_SUB_FUNCTION_NOT_SUPPORTED: 0x12,
  NRC_INCORRECT_MESSAGE_LENGTH: 0x13,
  NRC_CONDITIONS_NOT_CORRECT: 0x22,
  NRC_REQUEST_OUT_OF_RANGE: 0x31,
  NRC_SECURITY_ACCESS_DENIED: 0x33,
} as const;

/** Standard OBD2 Mode 01 PID definitions */
export const STANDARD_PIDS: Record<number, PIDDefinition> = {
  0x00: {
    pid: 0x00,
    service: OBD2Service.CURRENT_DATA,
    name: 'SUPPORTED_PIDS_01_20',
    description: 'PIDs supported [01-20]',
    unit: 'bitfield',
    dataType: PIDDataType.BITFIELD,
    min: 0,
    max: 0xFFFFFFFF,
    formula: 'A*0x1000000 + B*0x10000 + C*0x100 + D',
    byteCount: 4,
  },
  0x04: {
    pid: 0x04,
    service: OBD2Service.CURRENT_DATA,
    name: 'ENGINE_LOAD',
    description: 'Calculated engine load',
    unit: '%',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 100,
    formula: 'A/2.55',
    byteCount: 1,
  },
  0x05: {
    pid: 0x05,
    service: OBD2Service.CURRENT_DATA,
    name: 'COOLANT_TEMP',
    description: 'Engine coolant temperature',
    unit: '°C',
    dataType: PIDDataType.UINT8,
    min: -40,
    max: 215,
    formula: 'A - 40',
    byteCount: 1,
  },
  0x0C: {
    pid: 0x0C,
    service: OBD2Service.CURRENT_DATA,
    name: 'ENGINE_RPM',
    description: 'Engine speed',
    unit: 'rpm',
    dataType: PIDDataType.UINT16,
    min: 0,
    max: 16383.75,
    formula: '(A*256 + B)/4',
    byteCount: 2,
  },
  0x0D: {
    pid: 0x0D,
    service: OBD2Service.CURRENT_DATA,
    name: 'VEHICLE_SPEED',
    description: 'Vehicle speed',
    unit: 'km/h',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 255,
    formula: 'A',
    byteCount: 1,
  },
  0x0E: {
    pid: 0x0E,
    service: OBD2Service.CURRENT_DATA,
    name: 'TIMING_ADVANCE',
    description: 'Timing advance',
    unit: '° before TDC',
    dataType: PIDDataType.INT8,
    min: -64,
    max: 63.5,
    formula: 'A/2 - 64',
    byteCount: 1,
  },
  0x0F: {
    pid: 0x0F,
    service: OBD2Service.CURRENT_DATA,
    name: 'INTAKE_AIR_TEMP',
    description: 'Intake air temperature',
    unit: '°C',
    dataType: PIDDataType.UINT8,
    min: -40,
    max: 215,
    formula: 'A - 40',
    byteCount: 1,
  },
  0x10: {
    pid: 0x10,
    service: OBD2Service.CURRENT_DATA,
    name: 'MAF_FLOW_RATE',
    description: 'Mass air flow sensor air flow rate',
    unit: 'g/s',
    dataType: PIDDataType.UINT16,
    min: 0,
    max: 655.35,
    formula: '(A*256 + B)/100',
    byteCount: 2,
  },
  0x11: {
    pid: 0x11,
    service: OBD2Service.CURRENT_DATA,
    name: 'THROTTLE_POSITION',
    description: 'Throttle position',
    unit: '%',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 100,
    formula: 'A/2.55',
    byteCount: 1,
  },
  0x1F: {
    pid: 0x1F,
    service: OBD2Service.CURRENT_DATA,
    name: 'RUN_TIME',
    description: 'Run time since engine start',
    unit: 's',
    dataType: PIDDataType.UINT16,
    min: 0,
    max: 65535,
    formula: 'A*256 + B',
    byteCount: 2,
  },
  0x2F: {
    pid: 0x2F,
    service: OBD2Service.CURRENT_DATA,
    name: 'FUEL_LEVEL',
    description: 'Fuel tank level input',
    unit: '%',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 100,
    formula: 'A/2.55',
    byteCount: 1,
  },
  0x42: {
    pid: 0x42,
    service: OBD2Service.CURRENT_DATA,
    name: 'CONTROL_MODULE_VOLTAGE',
    description: 'Control module voltage',
    unit: 'V',
    dataType: PIDDataType.UINT16,
    min: 0,
    max: 65.535,
    formula: '(A*256 + B)/1000',
    byteCount: 2,
  },
  0x46: {
    pid: 0x46,
    service: OBD2Service.CURRENT_DATA,
    name: 'AMBIENT_AIR_TEMP',
    description: 'Ambient air temperature',
    unit: '°C',
    dataType: PIDDataType.UINT8,
    min: -40,
    max: 215,
    formula: 'A - 40',
    byteCount: 1,
  },
  0x5C: {
    pid: 0x5C,
    service: OBD2Service.CURRENT_DATA,
    name: 'OIL_TEMP',
    description: 'Engine oil temperature',
    unit: '°C',
    dataType: PIDDataType.UINT8,
    min: -40,
    max: 210,
    formula: 'A - 40',
    byteCount: 1,
  },
};

/** DTC category prefixes */
export const DTC_CATEGORY_MAP: Record<number, string> = {
  0: 'P0',
  1: 'P1',
  2: 'P2',
  3: 'P3',
  4: 'C0',
  5: 'C1',
  6: 'C2',
  7: 'C3',
  8: 'B0',
  9: 'B1',
  10: 'B2',
  11: 'B3',
  12: 'U0',
  13: 'U1',
  14: 'U2',
  15: 'U3',
};

/** Maximum number of DTCs per response */
export const MAX_DTC_PER_RESPONSE = 3;

/** OBD2 communication timeouts (ms) */
export const TIMEOUTS = {
  DEFAULT: 2000,
  LONG: 5000,
  INIT: 3000,
  FAST_INIT: 300,
} as const;

/** Baud rates for serial communication */
export const BAUD_RATES = [9600, 19200, 38400, 57600, 115200] as const;
