import { PIDDefinition, OBD2Service, PIDDataType } from '../../types';

export const EMISSIONS_PIDS: PIDDefinition[] = [
  {
    pid: 0x14,
    service: OBD2Service.CURRENT_DATA,
    name: 'Oxygen Sensor 1 - Bank 1',
    description: 'O2 sensor voltage and short term fuel trim - bank 1, sensor 1',
    unit: 'V',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 1.275,
    formula: 'A / 200',
    byteCount: 2,
    supported: true,
  },
  {
    pid: 0x15,
    service: OBD2Service.CURRENT_DATA,
    name: 'Oxygen Sensor 2 - Bank 1',
    description: 'O2 sensor voltage and short term fuel trim - bank 1, sensor 2',
    unit: 'V',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 1.275,
    formula: 'A / 200',
    byteCount: 2,
    supported: true,
  },
  {
    pid: 0x16,
    service: OBD2Service.CURRENT_DATA,
    name: 'Oxygen Sensor 3 - Bank 1',
    description: 'O2 sensor voltage and short term fuel trim - bank 1, sensor 3',
    unit: 'V',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 1.275,
    formula: 'A / 200',
    byteCount: 2,
    supported: true,
  },
  {
    pid: 0x17,
    service: OBD2Service.CURRENT_DATA,
    name: 'Oxygen Sensor 4 - Bank 1',
    description: 'O2 sensor voltage and short term fuel trim - bank 1, sensor 4',
    unit: 'V',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 1.275,
    formula: 'A / 200',
    byteCount: 2,
    supported: true,
  },
  {
    pid: 0x18,
    service: OBD2Service.CURRENT_DATA,
    name: 'Oxygen Sensor 1 - Bank 2',
    description: 'O2 sensor voltage and short term fuel trim - bank 2, sensor 1',
    unit: 'V',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 1.275,
    formula: 'A / 200',
    byteCount: 2,
    supported: true,
  },
  {
    pid: 0x19,
    service: OBD2Service.CURRENT_DATA,
    name: 'Oxygen Sensor 2 - Bank 2',
    description: 'O2 sensor voltage and short term fuel trim - bank 2, sensor 2',
    unit: 'V',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 1.275,
    formula: 'A / 200',
    byteCount: 2,
    supported: true,
  },
  {
    pid: 0x1A,
    service: OBD2Service.CURRENT_DATA,
    name: 'Oxygen Sensor 3 - Bank 2',
    description: 'O2 sensor voltage and short term fuel trim - bank 2, sensor 3',
    unit: 'V',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 1.275,
    formula: 'A / 200',
    byteCount: 2,
    supported: true,
  },
  {
    pid: 0x1B,
    service: OBD2Service.CURRENT_DATA,
    name: 'Oxygen Sensor 4 - Bank 2',
    description: 'O2 sensor voltage and short term fuel trim - bank 2, sensor 4',
    unit: 'V',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 1.275,
    formula: 'A / 200',
    byteCount: 2,
    supported: true,
  },
  {
    pid: 0x21,
    service: OBD2Service.CURRENT_DATA,
    name: 'Distance Traveled with MIL On',
    description: 'Distance traveled while malfunction indicator lamp is on',
    unit: 'km',
    dataType: PIDDataType.UINT16,
    min: 0,
    max: 65535,
    formula: '(A * 256) + B',
    byteCount: 2,
    supported: true,
  },
  {
    pid: 0x2C,
    service: OBD2Service.CURRENT_DATA,
    name: 'Commanded EGR',
    description: 'Commanded EGR valve position',
    unit: '%',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 100,
    formula: 'A * 100 / 255',
    byteCount: 1,
    supported: true,
  },
  {
    pid: 0x2D,
    service: OBD2Service.CURRENT_DATA,
    name: 'EGR Error',
    description: 'EGR error percentage',
    unit: '%',
    dataType: PIDDataType.INT8,
    min: -100,
    max: 99.2,
    formula: '(A - 128) * 100 / 128',
    byteCount: 1,
    supported: true,
  },
  {
    pid: 0x32,
    service: OBD2Service.CURRENT_DATA,
    name: 'Evap System Vapor Pressure',
    description: 'Evaporative system vapor pressure',
    unit: 'Pa',
    dataType: PIDDataType.INT16,
    min: -8192,
    max: 8192,
    formula: '((A * 256) + B) / 4',
    byteCount: 2,
    supported: true,
  },
  {
    pid: 0x3C,
    service: OBD2Service.CURRENT_DATA,
    name: 'Catalyst Temperature Bank 1 Sensor 1',
    description: 'Catalyst temperature - bank 1, sensor 1',
    unit: '°C',
    dataType: PIDDataType.UINT16,
    min: -40,
    max: 6513.5,
    formula: '((A * 256) + B) / 10 - 40',
    byteCount: 2,
    supported: true,
  },
  {
    pid: 0x3D,
    service: OBD2Service.CURRENT_DATA,
    name: 'Catalyst Temperature Bank 2 Sensor 1',
    description: 'Catalyst temperature - bank 2, sensor 1',
    unit: '°C',
    dataType: PIDDataType.UINT16,
    min: -40,
    max: 6513.5,
    formula: '((A * 256) + B) / 10 - 40',
    byteCount: 2,
    supported: true,
  },
  {
    pid: 0x3E,
    service: OBD2Service.CURRENT_DATA,
    name: 'Catalyst Temperature Bank 1 Sensor 2',
    description: 'Catalyst temperature - bank 1, sensor 2',
    unit: '°C',
    dataType: PIDDataType.UINT16,
    min: -40,
    max: 6513.5,
    formula: '((A * 256) + B) / 10 - 40',
    byteCount: 2,
    supported: true,
  },
  {
    pid: 0x3F,
    service: OBD2Service.CURRENT_DATA,
    name: 'Catalyst Temperature Bank 2 Sensor 2',
    description: 'Catalyst temperature - bank 2, sensor 2',
    unit: '°C',
    dataType: PIDDataType.UINT16,
    min: -40,
    max: 6513.5,
    formula: '((A * 256) + B) / 10 - 40',
    byteCount: 2,
    supported: true,
  },
  {
    pid: 0x2E,
    service: OBD2Service.CURRENT_DATA,
    name: 'Commanded Evaporative Purge',
    description: 'Commanded evaporative purge valve position',
    unit: '%',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 100,
    formula: 'A * 100 / 255',
    byteCount: 1,
    supported: true,
  },
  {
    pid: 0x30,
    service: OBD2Service.CURRENT_DATA,
    name: 'Warm-ups Since Codes Cleared',
    description: 'Number of warm-up cycles since diagnostic trouble codes cleared',
    unit: 'count',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 255,
    formula: 'A',
    byteCount: 1,
    supported: true,
  },
  {
    pid: 0x31,
    service: OBD2Service.CURRENT_DATA,
    name: 'Distance Since Codes Cleared',
    description: 'Distance traveled since diagnostic trouble codes cleared',
    unit: 'km',
    dataType: PIDDataType.UINT16,
    min: 0,
    max: 65535,
    formula: '(A * 256) + B',
    byteCount: 2,
    supported: true,
  },
  {
    pid: 0x4D,
    service: OBD2Service.CURRENT_DATA,
    name: 'Time Run with MIL On',
    description: 'Time run with malfunction indicator lamp on',
    unit: 'min',
    dataType: PIDDataType.UINT16,
    min: 0,
    max: 65535,
    formula: '(A * 256) + B',
    byteCount: 2,
    supported: true,
  },
  {
    pid: 0x4E,
    service: OBD2Service.CURRENT_DATA,
    name: 'Time Since Codes Cleared',
    description: 'Time since diagnostic trouble codes cleared',
    unit: 'min',
    dataType: PIDDataType.UINT16,
    min: 0,
    max: 65535,
    formula: '(A * 256) + B',
    byteCount: 2,
    supported: true,
  },
];
