import { PIDDefinition, PIDMode } from '../../types/pid';

export const EMISSION_PIDS: PIDDefinition[] = [
  {
    mode: PIDMode.CURRENT_DATA,
    pid: 0x14,
    name: 'O2_SENSOR_1_VOLTAGE',
    description: 'O2 Sensor 1 voltage',
    minValue: 0,
    maxValue: 1.275,
    unit: 'V',
    bytes: 2,
    formula: (bytes) => bytes[0] / 200,
  },
  {
    mode: PIDMode.CURRENT_DATA,
    pid: 0x15,
    name: 'O2_SENSOR_2_VOLTAGE',
    description: 'O2 Sensor 2 voltage',
    minValue: 0,
    maxValue: 1.275,
    unit: 'V',
    bytes: 2,
    formula: (bytes) => bytes[0] / 200,
  },
  {
    mode: PIDMode.CURRENT_DATA,
    pid: 0x1C,
    name: 'OBD_STANDARDS',
    description: 'OBD standards vehicle conforms to',
    minValue: 1,
    maxValue: 255,
    unit: '',
    bytes: 1,
    formula: (bytes) => bytes[0],
  },
  {
    mode: PIDMode.CURRENT_DATA,
    pid: 0x1F,
    name: 'RUN_TIME_SINCE_START',
    description: 'Run time since engine start',
    minValue: 0,
    maxValue: 65535,
    unit: 's',
    bytes: 2,
    formula: (bytes) => (bytes[0] * 256) + bytes[1],
  },
  {
    mode: PIDMode.CURRENT_DATA,
    pid: 0x21,
    name: 'DISTANCE_WITH_MIL',
    description: 'Distance traveled with MIL on',
    minValue: 0,
    maxValue: 65535,
    unit: 'km',
    bytes: 2,
    formula: (bytes) => (bytes[0] * 256) + bytes[1],
  },
  {
    mode: PIDMode.CURRENT_DATA,
    pid: 0x2C,
    name: 'COMMANDED_EGR',
    description: 'Commanded EGR',
    minValue: 0,
    maxValue: 100,
    unit: '%',
    bytes: 1,
    formula: (bytes) => (bytes[0] / 255) * 100,
  },
  {
    mode: PIDMode.CURRENT_DATA,
    pid: 0x2E,
    name: 'COMMANDED_EVAP_PURGE',
    description: 'Commanded evaporative purge',
    minValue: 0,
    maxValue: 100,
    unit: '%',
    bytes: 1,
    formula: (bytes) => (bytes[0] / 255) * 100,
  },
];
