import { PIDDefinition, OBD2Service, PIDDataType } from '../../types';

export const ENGINE_PIDS: PIDDefinition[] = [
  {
    pid: 0x04,
    service: OBD2Service.CURRENT_DATA,
    name: 'Engine Load',
    description: 'Calculated engine load value',
    unit: '%',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 100,
    formula: 'A * 100 / 255',
    byteCount: 1,
    supported: true,
  },
  {
    pid: 0x05,
    service: OBD2Service.CURRENT_DATA,
    name: 'Engine Coolant Temperature',
    description: 'Engine coolant temperature',
    unit: '°C',
    dataType: PIDDataType.UINT8,
    min: -40,
    max: 215,
    formula: 'A - 40',
    byteCount: 1,
    supported: true,
  },
  {
    pid: 0x0B,
    service: OBD2Service.CURRENT_DATA,
    name: 'Intake Manifold Absolute Pressure',
    description: 'Intake manifold absolute pressure (MAP)',
    unit: 'kPa',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 255,
    formula: 'A',
    byteCount: 1,
    supported: true,
  },
  {
    pid: 0x0C,
    service: OBD2Service.CURRENT_DATA,
    name: 'Engine RPM',
    description: 'Engine revolutions per minute',
    unit: 'RPM',
    dataType: PIDDataType.UINT16,
    min: 0,
    max: 16383.75,
    formula: '((A * 256) + B) / 4',
    byteCount: 2,
    supported: true,
  },
  {
    pid: 0x0D,
    service: OBD2Service.CURRENT_DATA,
    name: 'Vehicle Speed',
    description: 'Vehicle speed sensor reading',
    unit: 'km/h',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 255,
    formula: 'A',
    byteCount: 1,
    supported: true,
  },
  {
    pid: 0x0E,
    service: OBD2Service.CURRENT_DATA,
    name: 'Timing Advance',
    description: 'Timing advance relative to TDC on compression stroke',
    unit: '° before TDC',
    dataType: PIDDataType.INT8,
    min: -64,
    max: 63.5,
    formula: 'A / 2 - 64',
    byteCount: 1,
    supported: true,
  },
  {
    pid: 0x0F,
    service: OBD2Service.CURRENT_DATA,
    name: 'Intake Air Temperature',
    description: 'Intake air temperature',
    unit: '°C',
    dataType: PIDDataType.UINT8,
    min: -40,
    max: 215,
    formula: 'A - 40',
    byteCount: 1,
    supported: true,
  },
  {
    pid: 0x10,
    service: OBD2Service.CURRENT_DATA,
    name: 'Mass Air Flow Rate',
    description: 'Mass air flow sensor air flow rate',
    unit: 'g/s',
    dataType: PIDDataType.UINT16,
    min: 0,
    max: 655.35,
    formula: '((A * 256) + B) / 100',
    byteCount: 2,
    supported: true,
  },
  {
    pid: 0x11,
    service: OBD2Service.CURRENT_DATA,
    name: 'Throttle Position',
    description: 'Absolute throttle position',
    unit: '%',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 100,
    formula: 'A * 100 / 255',
    byteCount: 1,
    supported: true,
  },
  {
    pid: 0x1F,
    service: OBD2Service.CURRENT_DATA,
    name: 'Run Time Since Engine Start',
    description: 'Time run with MIL on or time since engine start',
    unit: 's',
    dataType: PIDDataType.UINT16,
    min: 0,
    max: 65535,
    formula: '(A * 256) + B',
    byteCount: 2,
    supported: true,
  },
  {
    pid: 0x43,
    service: OBD2Service.CURRENT_DATA,
    name: 'Absolute Load Value',
    description: 'Absolute load value',
    unit: '%',
    dataType: PIDDataType.UINT16,
    min: 0,
    max: 25700,
    formula: '((A * 256) + B) * 100 / 255',
    byteCount: 2,
    supported: true,
  },
  {
    pid: 0x46,
    service: OBD2Service.CURRENT_DATA,
    name: 'Ambient Air Temperature',
    description: 'Ambient air temperature',
    unit: '°C',
    dataType: PIDDataType.UINT8,
    min: -40,
    max: 215,
    formula: 'A - 40',
    byteCount: 1,
    supported: true,
  },
  {
    pid: 0x5C,
    service: OBD2Service.CURRENT_DATA,
    name: 'Engine Oil Temperature',
    description: 'Engine oil temperature',
    unit: '°C',
    dataType: PIDDataType.UINT8,
    min: -40,
    max: 210,
    formula: 'A - 40',
    byteCount: 1,
    supported: true,
  },
  {
    pid: 0x70,
    service: OBD2Service.CURRENT_DATA,
    name: 'Boost Pressure Control',
    description: 'Turbocharger boost pressure control',
    unit: 'kPa',
    dataType: PIDDataType.UINT16,
    min: 0,
    max: 65535,
    formula: '((A * 256) + B) * 0.03125',
    byteCount: 4,
    supported: true,
  },
  {
    pid: 0xA6,
    service: OBD2Service.CURRENT_DATA,
    name: 'Engine Friction Torque',
    description: 'Engine friction percent torque',
    unit: '%',
    dataType: PIDDataType.UINT16,
    min: -125,
    max: 130,
    formula: '((A * 256) + B) / 128 - 125',
    byteCount: 2,
    supported: true,
  },
  {
    pid: 0x4C,
    service: OBD2Service.CURRENT_DATA,
    name: 'Commanded Throttle Actuator',
    description: 'Commanded throttle actuator',
    unit: '%',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 100,
    formula: 'A * 100 / 255',
    byteCount: 1,
    supported: true,
  },
  {
    pid: 0x42,
    service: OBD2Service.CURRENT_DATA,
    name: 'Control Module Voltage',
    description: 'ECU/control module supply voltage',
    unit: 'V',
    dataType: PIDDataType.UINT16,
    min: 0,
    max: 65.535,
    formula: '((A * 256) + B) / 1000',
    byteCount: 2,
    supported: true,
  },
  {
    pid: 0x5A,
    service: OBD2Service.CURRENT_DATA,
    name: 'Relative Accelerator Pedal Position',
    description: 'Relative accelerator pedal position',
    unit: '%',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 100,
    formula: 'A * 100 / 255',
    byteCount: 1,
    supported: true,
  },
  {
    pid: 0x5B,
    service: OBD2Service.CURRENT_DATA,
    name: 'Hybrid Battery Pack Remaining Life',
    description: 'Hybrid battery pack remaining life',
    unit: '%',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 100,
    formula: 'A * 100 / 255',
    byteCount: 1,
    supported: true,
  },
  {
    pid: 0x5D,
    service: OBD2Service.CURRENT_DATA,
    name: 'Fuel Injection Timing',
    description: 'Fuel injection timing',
    unit: '°',
    dataType: PIDDataType.UINT16,
    min: -210,
    max: 301.992,
    formula: '((A * 256) + B - 26880) / 128',
    byteCount: 2,
    supported: true,
  },
];
