import { PIDDefinition, PIDMode } from '../../types/pid';

export const ENGINE_PIDS: PIDDefinition[] = [
  {
    mode: PIDMode.CURRENT_DATA,
    pid: 0x04,
    name: 'CALC_ENGINE_LOAD',
    description: 'Calculated engine load',
    minValue: 0,
    maxValue: 100,
    unit: '%',
    bytes: 1,
    formula: (bytes) => (bytes[0] / 255) * 100,
  },
  {
    mode: PIDMode.CURRENT_DATA,
    pid: 0x05,
    name: 'ENGINE_COOLANT_TEMP',
    description: 'Engine coolant temperature',
    minValue: -40,
    maxValue: 215,
    unit: '°C',
    bytes: 1,
    formula: (bytes) => bytes[0] - 40,
  },
  {
    mode: PIDMode.CURRENT_DATA,
    pid: 0x0C,
    name: 'ENGINE_RPM',
    description: 'Engine RPM',
    minValue: 0,
    maxValue: 16383.75,
    unit: 'RPM',
    bytes: 2,
    formula: (bytes) => ((bytes[0] * 256) + bytes[1]) / 4,
  },
  {
    mode: PIDMode.CURRENT_DATA,
    pid: 0x0D,
    name: 'VEHICLE_SPEED',
    description: 'Vehicle speed',
    minValue: 0,
    maxValue: 255,
    unit: 'km/h',
    bytes: 1,
    formula: (bytes) => bytes[0],
  },
  {
    mode: PIDMode.CURRENT_DATA,
    pid: 0x0E,
    name: 'TIMING_ADVANCE',
    description: 'Timing advance',
    minValue: -64,
    maxValue: 63.5,
    unit: '° before TDC',
    bytes: 1,
    formula: (bytes) => (bytes[0] / 2) - 64,
  },
  {
    mode: PIDMode.CURRENT_DATA,
    pid: 0x0F,
    name: 'INTAKE_AIR_TEMP',
    description: 'Intake air temperature',
    minValue: -40,
    maxValue: 215,
    unit: '°C',
    bytes: 1,
    formula: (bytes) => bytes[0] - 40,
  },
  {
    mode: PIDMode.CURRENT_DATA,
    pid: 0x10,
    name: 'MAF_AIR_FLOW_RATE',
    description: 'Mass air flow sensor (MAF) air flow rate',
    minValue: 0,
    maxValue: 655.35,
    unit: 'g/s',
    bytes: 2,
    formula: (bytes) => ((bytes[0] * 256) + bytes[1]) / 100,
  },
  {
    mode: PIDMode.CURRENT_DATA,
    pid: 0x11,
    name: 'THROTTLE_POSITION',
    description: 'Throttle position',
    minValue: 0,
    maxValue: 100,
    unit: '%',
    bytes: 1,
    formula: (bytes) => (bytes[0] / 255) * 100,
  },
  {
    mode: PIDMode.CURRENT_DATA,
    pid: 0x5C,
    name: 'ENGINE_OIL_TEMP',
    description: 'Engine oil temperature',
    minValue: -40,
    maxValue: 210,
    unit: '°C',
    bytes: 1,
    formula: (bytes) => bytes[0] - 40,
  },
];
