import { PIDDefinition, OBD2Service, PIDDataType } from '../../types';

export const FUEL_PIDS: PIDDefinition[] = [
  {
    pid: 0x03,
    service: OBD2Service.CURRENT_DATA,
    name: 'Fuel System Status',
    description: 'Fuel system closed/open loop status',
    unit: '',
    dataType: PIDDataType.BITFIELD,
    min: 0,
    max: 255,
    formula: 'A',
    byteCount: 2,
    supported: true,
  },
  {
    pid: 0x06,
    service: OBD2Service.CURRENT_DATA,
    name: 'Short Term Fuel Trim Bank 1',
    description: 'Short term fuel trim - bank 1',
    unit: '%',
    dataType: PIDDataType.INT8,
    min: -100,
    max: 99.2,
    formula: '(A - 128) * 100 / 128',
    byteCount: 1,
    supported: true,
  },
  {
    pid: 0x07,
    service: OBD2Service.CURRENT_DATA,
    name: 'Long Term Fuel Trim Bank 1',
    description: 'Long term fuel trim - bank 1',
    unit: '%',
    dataType: PIDDataType.INT8,
    min: -100,
    max: 99.2,
    formula: '(A - 128) * 100 / 128',
    byteCount: 1,
    supported: true,
  },
  {
    pid: 0x08,
    service: OBD2Service.CURRENT_DATA,
    name: 'Short Term Fuel Trim Bank 2',
    description: 'Short term fuel trim - bank 2',
    unit: '%',
    dataType: PIDDataType.INT8,
    min: -100,
    max: 99.2,
    formula: '(A - 128) * 100 / 128',
    byteCount: 1,
    supported: true,
  },
  {
    pid: 0x09,
    service: OBD2Service.CURRENT_DATA,
    name: 'Long Term Fuel Trim Bank 2',
    description: 'Long term fuel trim - bank 2',
    unit: '%',
    dataType: PIDDataType.INT8,
    min: -100,
    max: 99.2,
    formula: '(A - 128) * 100 / 128',
    byteCount: 1,
    supported: true,
  },
  {
    pid: 0x0A,
    service: OBD2Service.CURRENT_DATA,
    name: 'Fuel Pressure',
    description: 'Fuel pressure (gauge)',
    unit: 'kPa',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 765,
    formula: 'A * 3',
    byteCount: 1,
    supported: true,
  },
  {
    pid: 0x2F,
    service: OBD2Service.CURRENT_DATA,
    name: 'Fuel Tank Level Input',
    description: 'Fuel tank level percentage',
    unit: '%',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 100,
    formula: 'A * 100 / 255',
    byteCount: 1,
    supported: true,
  },
  {
    pid: 0x33,
    service: OBD2Service.CURRENT_DATA,
    name: 'Absolute Barometric Pressure',
    description: 'Absolute barometric pressure',
    unit: 'kPa',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 255,
    formula: 'A',
    byteCount: 1,
    supported: true,
  },
  {
    pid: 0x44,
    service: OBD2Service.CURRENT_DATA,
    name: 'Commanded Equivalence Ratio',
    description: 'Commanded air-fuel equivalence ratio (lambda)',
    unit: '',
    dataType: PIDDataType.UINT16,
    min: 0,
    max: 2,
    formula: '((A * 256) + B) * 2 / 65535',
    byteCount: 2,
    supported: true,
  },
  {
    pid: 0x45,
    service: OBD2Service.CURRENT_DATA,
    name: 'Relative Throttle Position',
    description: 'Relative throttle position',
    unit: '%',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 100,
    formula: 'A * 100 / 255',
    byteCount: 1,
    supported: true,
  },
  {
    pid: 0x47,
    service: OBD2Service.CURRENT_DATA,
    name: 'Absolute Throttle Position B',
    description: 'Absolute throttle position B',
    unit: '%',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 100,
    formula: 'A * 100 / 255',
    byteCount: 1,
    supported: true,
  },
  {
    pid: 0x48,
    service: OBD2Service.CURRENT_DATA,
    name: 'Absolute Throttle Position C',
    description: 'Absolute throttle position C',
    unit: '%',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 100,
    formula: 'A * 100 / 255',
    byteCount: 1,
    supported: true,
  },
  {
    pid: 0x49,
    service: OBD2Service.CURRENT_DATA,
    name: 'Accelerator Pedal Position D',
    description: 'Accelerator pedal position D',
    unit: '%',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 100,
    formula: 'A * 100 / 255',
    byteCount: 1,
    supported: true,
  },
  {
    pid: 0x4A,
    service: OBD2Service.CURRENT_DATA,
    name: 'Accelerator Pedal Position E',
    description: 'Accelerator pedal position E',
    unit: '%',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 100,
    formula: 'A * 100 / 255',
    byteCount: 1,
    supported: true,
  },
  {
    pid: 0x4B,
    service: OBD2Service.CURRENT_DATA,
    name: 'Accelerator Pedal Position F',
    description: 'Accelerator pedal position F',
    unit: '%',
    dataType: PIDDataType.UINT8,
    min: 0,
    max: 100,
    formula: 'A * 100 / 255',
    byteCount: 1,
    supported: true,
  },
  {
    pid: 0x5E,
    service: OBD2Service.CURRENT_DATA,
    name: 'Engine Fuel Rate',
    description: 'Engine fuel rate',
    unit: 'L/h',
    dataType: PIDDataType.UINT16,
    min: 0,
    max: 3212.75,
    formula: '((A * 256) + B) * 0.05',
    byteCount: 2,
    supported: true,
  },
  {
    pid: 0x22,
    service: OBD2Service.CURRENT_DATA,
    name: 'Fuel Rail Pressure (Relative to Manifold Vacuum)',
    description: 'Fuel rail pressure relative to manifold vacuum',
    unit: 'kPa',
    dataType: PIDDataType.UINT16,
    min: 0,
    max: 5177.265,
    formula: '((A * 256) + B) * 0.079',
    byteCount: 2,
    supported: true,
  },
  {
    pid: 0x23,
    service: OBD2Service.CURRENT_DATA,
    name: 'Fuel Rail Gauge Pressure',
    description: 'Fuel rail gauge pressure (direct injection)',
    unit: 'kPa',
    dataType: PIDDataType.UINT16,
    min: 0,
    max: 655350,
    formula: '((A * 256) + B) * 10',
    byteCount: 2,
    supported: true,
  },
];
